[package]
name = "general_vit"
version = "0.1.0"
edition = "2024"
rust-version = "1.88.0"
publish = false

[[bin]]
name = "general_vit"
path = "src/main.rs"
test = false
bench = false
doc = false

[dependencies]
rusty-vit = { workspace = true }
clap = { workspace = true, features = ["derive"] }

